FROM python

# INSTALL DEPENDENCIES
RUN apt update
RUN apt -y install sudo
RUN apt -y install cron
RUN apt -y install vim
RUN apt -y install openssh-server

# CREATE SEPARATE USER FOR WEB APP
RUN useradd --no-log-init -ms /usr/sbin/nologin crashboard
RUN sudo usermod -aG shadow crashboard
WORKDIR /home/crashboard/

# INSTALL PYTHON DEPS
USER crashboard
COPY requirements.txt .
RUN python3 -m venv venv
RUN ./venv/bin/pip install --no-cache-dir -r requirements.txt
USER root